import path from 'path';
import { parse } from 'node-html-parser';
import * as pi from 'picocolors';
import * as svgo from 'svgo';
import { PresetDefaultOverrides } from 'svgo/plugins/plugins-types';
import { IconData } from '../types';
import { composeFileName, writeFile } from './files';
import { getByteSize, getHash, outputFileNames } from './helpers';

type SymbolProps = { name: string; content: string };
export function convertToSymbol({ name, content }: SymbolProps) {
  const svgRoot = parse(content);
  const svg = svgRoot.getElementsByTagName('svg')[0];
  if (!svg) throw new Error('Unable to parse svg contents');

  svg.tagName = 'symbol'; // rename the tag
  svg.setAttribute('id', name); // give icon id

  const presetOverrides: PresetDefaultOverrides = {
    cleanupIds: false,
    removeHiddenElems: false,
    removeViewBox: false,
  };

  const removeAttrs = ['xmlns'];

  const output = svgo.optimize(svg.toString(), {
    floatPrecision: 2,
    plugins: [
      { name: 'preset-default', params: { overrides: presetOverrides } },
      { name: 'removeAttrs', params: { attrs: removeAttrs } },
    ],
  });

  return output.data;
}

type SpriteFileProps = {
  svgIcons: IconData[];
  outputPath: string;
  cwd: string;
};
export async function createSpriteFiles({
  svgIcons,
  outputPath,
  cwd,
}: SpriteFileProps) {
  const files = outputFileNames(outputPath);

  // sprite symbols
  const symbols = svgIcons.map(convertToSymbol);
  const spriteContent = [
    `<?xml version="1.0" encoding="utf-8"?>`,
    `<!-- This file is generated by @oviirup/sprite -->`,
    `<svg xmlns="http://www.w3.org/2000/svg">`,
    ...symbols,
    `</svg>`,
  ].join('\n');
  await writeFile(files.sprite, spriteContent).then((res) => {
    if (!res) return;
    const relativePath = path.relative(cwd, files.sprite);
    console.log(pi.green('✓'), pi.dim('sprite:'), relativePath);
  });

  // sprite metadata
  const metadata = Object.fromEntries(svgIcons.map((e) => [e.name, 0]));
  const metaContent = JSON.stringify(metadata);
  await writeFile(files.meta, metaContent).then((res) => {
    if (!res) return;
    const relativePath = path.relative(cwd, files.meta);
    console.log(pi.green('✓'), pi.dim('meta:  '), relativePath);
  });
}
